name: API

on:
  workflow_run:
    workflows: [Bundle/yarn update]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: docker-compose up
        run: |
          echo test
          
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update dependencies ${{ steps.date.outputs.current }}
          title: Update dependencies (${{ steps.date.outputs.current }})
          branch: bundle-update-${{ steps.date.outputs.current }}
