name: Bundle/yarn update

# 毎週月曜に実行
on:
  push:

jobs:
  createPullRequest:
    runs-on: ubuntu-latest

    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=current::$(date +'%Y/%m/%d')"

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update dependencies ${{ steps.date.outputs.current }}
          title: Update dependencies (${{ steps.date.outputs.current }})
          branch: bundle-update-${{ steps.date.outputs.current }}
